#pragma once

#include <reflect/meta.hpp>
#include <reflect/query.hpp>
#include <reflect/schema.hpp>
#include <reflect/value.hpp>

#include <algorithm>
#include <cstddef>
#include <iterator>
#include <optional>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace reflect
{

struct statement
{
    std::string            sql;
    std::vector<sql_value> binds;
};

namespace detail
{

inline void append_joined_identifiers(std::string& output, const std::vector<column_descriptor>& columns)
{
    for(std::size_t index = 0; index < columns.size(); ++index)
    {
        if(index != 0)
        {
            output.append(", ");
        }

        output.append(quote_identifier(columns[index].name));
    }
}

inline void append_placeholders(std::string& output, std::size_t count)
{
    for(std::size_t index = 0; index < count; ++index)
    {
        if(index != 0)
        {
            output.append(", ");
        }

        output.push_back('?');
    }
}

inline void append_orderings(std::string& output, const std::vector<ordering>& orderings)
{
    if(orderings.empty())
    {
        return;
    }

    output.append(" ORDER BY ");
    for(std::size_t index = 0; index < orderings.size(); ++index)
    {
        if(index != 0)
        {
            output.append(", ");
        }

        output.append(quote_identifier(orderings[index].column));
        output.append(orderings[index].direction == sort_direction::ascending ? " ASC" : " DESC");
    }
}

template <typename Model>
inline void append_query_tail(std::string& sql, std::vector<sql_value>& binds, query_options<Model> options, bool include_ordering = true)
{
    if(!options.filter.empty())
    {
        sql.append(" WHERE ");
        sql.append(options.filter.sql);
        std::ranges::move(options.filter.binds, std::back_inserter(binds));
    }

    if(include_ordering)
    {
        append_orderings(sql, options.orderings);
    }

    if(options.limit)
    {
        sql.append(" LIMIT ");
        sql.append(std::to_string(*options.limit));
    }

    if(options.offset)
    {
        sql.append(" OFFSET ");
        sql.append(std::to_string(*options.offset));
    }
}

inline std::string column_definition(const column_descriptor& column, dialect target, bool alter_table)
{
    std::string output = quote_identifier(column.name);
    output.push_back(' ');

    if(column.flags.primary_key && column.flags.auto_increment && target == dialect::sqlite)
    {
        output.append("INTEGER PRIMARY KEY AUTOINCREMENT");
    }
    else
    {
        output.append(column.sql_type);

        if(column.flags.primary_key && column.flags.auto_increment && target == dialect::postgresql)
        {
            output.append(" GENERATED BY DEFAULT AS IDENTITY");
        }

        if(column.flags.primary_key)
        {
            output.append(" PRIMARY KEY");
        }
    }

    if(column.flags.not_null && !column.flags.primary_key)
    {
        output.append(" NOT NULL");
    }

    if(!column.default_sql.empty())
    {
        output.append(" DEFAULT ");
        output.append(column.default_sql);
    }

    if(!column.check_sql.empty())
    {
        output.append(" CHECK (");
        output.append(column.check_sql);
        output.push_back(')');
    }

    if(column.has_reference)
    {
        output.append(" REFERENCES ");
        output.append(quote_identifier(column.reference.table));
        output.append(" (");
        output.append(quote_identifier(column.reference.column));
        output.push_back(')');

        if(!column.reference.on_delete.empty())
        {
            output.append(" ON DELETE ");
            output.append(column.reference.on_delete);
        }

        if(!column.reference.on_update.empty())
        {
            output.append(" ON UPDATE ");
            output.append(column.reference.on_update);
        }
    }

    return output;
}

template <typename Model>
[[nodiscard]] Model materialize_row(const std::vector<sql_value>& row)
{
    Model       model{};
    std::size_t index = 0;

    meta::for_each_persistent_field<ignore_t>(model, [&](meta::field reflected_field, auto& value) {
        if(index >= row.size())
        {
            throw std::runtime_error{"reflect ORM result row has fewer columns than the model schema"};
        }

        try
        {
            assign_sql_value(row[index], value);
        }
        catch(const std::exception& error)
        {
            throw std::runtime_error{"reflect ORM failed to read column `" + std::string{reflected_field.name} + "`: " + error.what()};
        }

        ++index;
    });

    return model;
}

template <typename Model>
[[nodiscard]] sql_value primary_key_value(const Model& object, const model_descriptor<Model>& model)
{
    std::size_t descriptor_index = 0;
    std::optional<sql_value> output;

    meta::for_each_persistent_field<ignore_t>(object, [&](meta::field, const auto& value) {
        const auto& descriptor = model.columns[descriptor_index];
        if(descriptor.flags.primary_key)
        {
            output = to_sql_value(value);
        }

        ++descriptor_index;
    });

    if(!output)
    {
        throw std::logic_error{"reflect ORM failed to read primary key value from model"};
    }

    return std::move(*output);
}

} // namespace detail

template <typename Model>
[[nodiscard]] statement create_table(const model_descriptor<Model>& model)
{
    statement output;
    output.sql = "CREATE TABLE IF NOT EXISTS ";
    output.sql.append(detail::quote_identifier(model.table_name));
    output.sql.append(" (");

    for(std::size_t index = 0; index < model.columns.size(); ++index)
    {
        if(index != 0)
        {
            output.sql.append(", ");
        }

        output.sql.append(detail::column_definition(model.columns[index], model.target, false));
    }

    output.sql.push_back(')');
    return output;
}

template <typename Model>
[[nodiscard]] statement create_table(dialect target)
{
    return create_table(describe_model<Model>(target));
}

template <typename Model>
[[nodiscard]] statement add_column(const model_descriptor<Model>& model, const column_descriptor& descriptor)
{
    statement output;
    output.sql = "ALTER TABLE ";
    output.sql.append(detail::quote_identifier(model.table_name));
    output.sql.append(" ADD COLUMN ");
    output.sql.append(detail::column_definition(descriptor, model.target, true));
    return output;
}

template <typename Model>
[[nodiscard]] statement add_column(const column_descriptor& descriptor, dialect target)
{
    return add_column(describe_model<Model>(target), descriptor);
}

template <typename Model>
[[nodiscard]] std::vector<statement> create_index_statements(const model_descriptor<Model>& model)
{
    std::vector<statement> output;

    for(const auto& column: model.columns)
    {
        if(column.flags.primary_key || (!column.flags.indexed && !column.flags.unique))
        {
            continue;
        }

        statement index;
        index.sql = column.flags.unique ? "CREATE UNIQUE INDEX IF NOT EXISTS " : "CREATE INDEX IF NOT EXISTS ";

        const auto prefix = column.flags.unique ? "uidx_" : "idx_";
        index.sql.append(detail::quote_identifier(prefix + model.table_name + "_" + column.name));
        index.sql.append(" ON ");
        index.sql.append(detail::quote_identifier(model.table_name));
        index.sql.append(" (");
        index.sql.append(detail::quote_identifier(column.name));
        index.sql.push_back(')');
        output.emplace_back(std::move(index));
    }

    return output;
}

template <typename Model>
[[nodiscard]] std::vector<statement> create_index_statements(dialect target)
{
    return create_index_statements(describe_model<Model>(target));
}

template <typename Model>
[[nodiscard]] statement insert_statement(const Model& object, const model_descriptor<Model>& model)
{
    std::vector<column_descriptor> inserted_descriptors;
    inserted_descriptors.reserve(model.columns.size());

    for(const auto& descriptor: model.columns)
    {
        if(!descriptor.generated_on_insert)
        {
            inserted_descriptors.emplace_back(descriptor);
        }
    }

    statement output;
    output.sql = "INSERT INTO ";
    output.sql.append(detail::quote_identifier(model.table_name));

    if(inserted_descriptors.empty())
    {
        output.sql.append(" DEFAULT VALUES");
        return output;
    }

    output.sql.append(" (");
    detail::append_joined_identifiers(output.sql, inserted_descriptors);
    output.sql.append(") VALUES (");
    detail::append_placeholders(output.sql, inserted_descriptors.size());
    output.sql.push_back(')');

    std::size_t descriptor_index = 0;
    meta::for_each_persistent_field<ignore_t>(object, [&](meta::field, const auto& value) {
        const auto& descriptor = model.columns[descriptor_index];
        if(!descriptor.generated_on_insert)
        {
            output.binds.emplace_back(detail::to_sql_value(value));
        }

        ++descriptor_index;
    });

    return output;
}

template <typename Model>
[[nodiscard]] statement insert_statement(const Model& model, dialect target)
{
    return insert_statement(model, describe_model<Model>(target));
}

template <typename Model>
[[nodiscard]] statement update_statement(const Model& object, const model_descriptor<Model>& model)
{
    const auto primary_key = primary_key_column(model);

    statement output;
    output.sql = "UPDATE ";
    output.sql.append(detail::quote_identifier(model.table_name));
    output.sql.append(" SET ");

    bool        first = true;
    std::size_t descriptor_index = 0;
    std::optional<sql_value> key_bind;

    meta::for_each_persistent_field<ignore_t>(object, [&](meta::field, const auto& value) {
        const auto& descriptor = model.columns[descriptor_index];

        if(descriptor.flags.primary_key)
        {
            key_bind = detail::to_sql_value(value);
            ++descriptor_index;
            return;
        }

        if(descriptor.flags.updated_at && !descriptor.on_update_sql.empty())
        {
            if(!first)
            {
                output.sql.append(", ");
            }

            first = false;
            output.sql.append(detail::quote_identifier(descriptor.name));
            output.sql.append(" = ");
            output.sql.append(descriptor.on_update_sql);
            ++descriptor_index;
            return;
        }

        if(!first)
        {
            output.sql.append(", ");
        }

        first = false;
        output.sql.append(detail::quote_identifier(descriptor.name));
        output.sql.append(" = ?");
        output.binds.emplace_back(detail::to_sql_value(value));
        ++descriptor_index;
    });

    if(!key_bind)
    {
        throw std::logic_error{"reflect ORM update requires a primary key column"};
    }

    if(first)
    {
        throw std::logic_error{"reflect ORM update requires at least one non-primary-key column"};
    }

    output.sql.append(" WHERE ");
    output.sql.append(detail::quote_identifier(primary_key.name));
    output.sql.append(" = ?");
    output.binds.emplace_back(std::move(*key_bind));
    return output;
}

template <typename Model>
[[nodiscard]] statement update_many_statement(const Model& patch, const model_descriptor<Model>& model, condition filter)
{
    statement output;
    output.sql = "UPDATE ";
    output.sql.append(detail::quote_identifier(model.table_name));
    output.sql.append(" SET ");

    bool        first = true;
    std::size_t descriptor_index = 0;

    meta::for_each_persistent_field<ignore_t>(patch, [&](meta::field, const auto& value) {
        const auto& descriptor = model.columns[descriptor_index];

        if(descriptor.flags.primary_key || (descriptor.generated_on_insert && !descriptor.flags.updated_at))
        {
            ++descriptor_index;
            return;
        }

        if(!first)
        {
            output.sql.append(", ");
        }

        first = false;
        output.sql.append(detail::quote_identifier(descriptor.name));

        if(descriptor.flags.updated_at && !descriptor.on_update_sql.empty())
        {
            output.sql.append(" = ");
            output.sql.append(descriptor.on_update_sql);
        }
        else
        {
            output.sql.append(" = ?");
            output.binds.emplace_back(detail::to_sql_value(value));
        }

        ++descriptor_index;
    });

    if(first)
    {
        throw std::logic_error{"reflect ORM update_many requires at least one mutable column"};
    }

    if(!filter.empty())
    {
        output.sql.append(" WHERE ");
        output.sql.append(filter.sql);
        std::ranges::move(filter.binds, std::back_inserter(output.binds));
    }

    return output;
}

template <typename Model>
[[nodiscard]] statement update_many_statement(const Model& patch, condition filter, dialect target)
{
    return update_many_statement(patch, describe_model<Model>(target), std::move(filter));
}

template <typename Model>
[[nodiscard]] statement update_statement(const Model& model, dialect target)
{
    return update_statement(model, describe_model<Model>(target));
}

template <typename Model>
[[nodiscard]] statement select_statement(const model_descriptor<Model>& model, condition filter = {})
{
    statement output;
    output.sql = "SELECT ";
    detail::append_joined_identifiers(output.sql, model.columns);
    output.sql.append(" FROM ");
    output.sql.append(detail::quote_identifier(model.table_name));

    if(!filter.empty())
    {
        output.sql.append(" WHERE ");
        output.sql.append(filter.sql);
        output.binds = std::move(filter.binds);
    }

    return output;
}

template <typename Model>
[[nodiscard]] statement select_statement(const model_descriptor<Model>& model, query_options<Model> options)
{
    statement output;
    output.sql = "SELECT ";
    detail::append_joined_identifiers(output.sql, model.columns);
    output.sql.append(" FROM ");
    output.sql.append(detail::quote_identifier(model.table_name));
    detail::append_query_tail(output.sql, output.binds, std::move(options));
    return output;
}

template <typename Model>
[[nodiscard]] statement select_statement(query_options<Model> options, dialect target = dialect::sqlite)
{
    return select_statement(describe_model<Model>(target), std::move(options));
}

template <typename Model>
[[nodiscard]] statement select_statement(condition filter = {}, dialect target = dialect::sqlite)
{
    return select_statement(describe_model<Model>(target), std::move(filter));
}

template <typename Model>
[[nodiscard]] statement select_one_statement(const model_descriptor<Model>& model, condition filter = {})
{
    statement output = select_statement(model, std::move(filter));
    output.sql.append(" LIMIT 1");
    return output;
}

template <typename Model>
[[nodiscard]] statement select_one_statement(const model_descriptor<Model>& model, query_options<Model> options)
{
    options.limit = 1;
    return select_statement(model, std::move(options));
}

template <typename Model>
[[nodiscard]] statement select_one_statement(query_options<Model> options, dialect target = dialect::sqlite)
{
    return select_one_statement(describe_model<Model>(target), std::move(options));
}

template <typename Model>
[[nodiscard]] statement select_one_statement(condition filter = {}, dialect target = dialect::sqlite)
{
    return select_one_statement(describe_model<Model>(target), std::move(filter));
}

template <typename Model, typename Id>
[[nodiscard]] statement select_by_id_statement(const model_descriptor<Model>& model, const Id& id)
{
    const auto primary_key = primary_key_column(model);

    condition filter;
    filter.sql = detail::quote_identifier(primary_key.name) + " = ?";
    filter.binds.emplace_back(detail::to_sql_value(id));
    return select_one_statement(model, std::move(filter));
}

template <typename Model, typename Id>
[[nodiscard]] statement select_by_id_statement(const Id& id, dialect target)
{
    return select_by_id_statement(describe_model<Model>(target), id);
}

template <typename Model>
[[nodiscard]] statement delete_statement(const model_descriptor<Model>& model, condition filter)
{
    statement output;
    output.sql = "DELETE FROM ";
    output.sql.append(detail::quote_identifier(model.table_name));

    if(!filter.empty())
    {
        output.sql.append(" WHERE ");
        output.sql.append(filter.sql);
        output.binds = std::move(filter.binds);
    }

    return output;
}

template <typename Model>
[[nodiscard]] statement delete_statement(const model_descriptor<Model>& model, query_options<Model> options)
{
    statement output;
    output.sql = "DELETE FROM ";
    output.sql.append(detail::quote_identifier(model.table_name));
    detail::append_query_tail(output.sql, output.binds, std::move(options), false);
    return output;
}

template <typename Model>
[[nodiscard]] statement delete_statement(condition filter, dialect target)
{
    return delete_statement(describe_model<Model>(target), std::move(filter));
}

template <typename Model, typename Id>
[[nodiscard]] statement delete_by_id_statement(const model_descriptor<Model>& model, const Id& id)
{
    const auto primary_key = primary_key_column(model);

    condition filter;
    filter.sql = detail::quote_identifier(primary_key.name) + " = ?";
    filter.binds.emplace_back(detail::to_sql_value(id));
    return delete_statement(model, std::move(filter));
}

template <typename Model, typename Id>
[[nodiscard]] statement delete_by_id_statement(const Id& id, dialect target)
{
    return delete_by_id_statement(describe_model<Model>(target), id);
}

template <typename Model>
[[nodiscard]] statement count_statement(const model_descriptor<Model>& model, condition filter = {})
{
    statement output;
    output.sql = "SELECT COUNT(*) FROM ";
    output.sql.append(detail::quote_identifier(model.table_name));

    if(!filter.empty())
    {
        output.sql.append(" WHERE ");
        output.sql.append(filter.sql);
        output.binds = std::move(filter.binds);
    }

    return output;
}

template <typename Model>
[[nodiscard]] statement count_statement(const model_descriptor<Model>& model, query_options<Model> options)
{
    return count_statement(model, std::move(options.filter));
}

template <typename Model>
[[nodiscard]] statement exists_statement(const model_descriptor<Model>& model, condition filter = {})
{
    statement output;
    output.sql = "SELECT 1 FROM ";
    output.sql.append(detail::quote_identifier(model.table_name));

    if(!filter.empty())
    {
        output.sql.append(" WHERE ");
        output.sql.append(filter.sql);
        output.binds = std::move(filter.binds);
    }

    output.sql.append(" LIMIT 1");
    return output;
}

template <typename Model>
[[nodiscard]] statement exists_statement(const model_descriptor<Model>& model, query_options<Model> options)
{
    return exists_statement(model, std::move(options.filter));
}

template <typename Model>
[[nodiscard]] std::vector<statement> create_schema_statements(const model_descriptor<Model>& model)
{
    std::vector<statement> output;
    output.emplace_back(create_table(model));

    auto indexes = create_index_statements(model);
    std::ranges::move(indexes, std::back_inserter(output));

    return output;
}

template <typename Model>
[[nodiscard]] std::vector<statement> create_schema_statements(dialect target)
{
    return create_schema_statements(describe_model<Model>(target));
}

} // namespace reflect
